#pragma once
#define MAX 100
#define SIZECOEFINITIAL 20
#define INALTIME_MENIU_OPTIUNI 50
#define INALTIME_MENIU_ELEMENTE 50
#define PI 3.141592
#define LATIME_FEREASTRA 1920
#define INALTIME_FEREASTRA 1080
#define NUMAR_OPTIUNI_MENIU 7
#define MAX_LUNGIME_FISIER 30
#define OFFSET 15
#define MAXNUME 20
#define MAXNUMAR 7
#define NUMAR_ELEMENTE 12
#define NUMAR_AJUTOR_COMENZI 6